title: Anish Kulkarni
email: ackulkar@usc.edu
description: Portfolio website of Anish Kulkarni, a multidisciplinary engineer and product manager.
baseurl: "/portfolio"
url: "https://anikulkarn.github.io"

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
